[build-system]
requires = ["setuptools>=61.0", "packaging", "torch>=1.7.1", "ftfy", "regex", "tqdm"]
build-backend = "setuptools.build_meta"

[project]
name='clip'
description=''
requires-python = ">=3.10"
dynamic = ["dependencies", "version", "authors"]
